# -*- coding: utf-8 -*-
"""conditional looping1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OLn0T2N_64KPhG6kgvBrywRonmDvYAOy
"""

list2=[12,14,-95,3]
print("Positive numbers in",list2,"are: ")
  
#traversing
for i in list2:   
    # checking condition
    if i >= 0:
       print(i, end = " ")